language: python
sudo: false
python:
  - "2.7"
cache: pip
install:
  - pip install -U pip wheel
  - pip install -r requirements.txt
  - pip install -r requirements_test.txt
  - pip install coveralls
env:
  global:
    # Bucket managed by cloud.gov at eregs-nc/integration
    - BUCKET=cg-bcf4ec52-851a-4aaf-b353-acc25474a336
    - secure: "ErjIomoPl2CVB8kPkX6/yKZLBt/esvY6GnL/j9l3QTissOzyIKknCVaLDRsInyyZCBZKu1JhGHF2WI6xCTO8Ey6Mtl8lVkOE/7SPyoWVAuRujM4L13LCnaESVBk0y+GYwRlONsVP3CGGWe/iWQ6Dbx11euB1s1i0mwVgcvvRphE="
    - secure: "I7SpIvavHAw9ObcJlJJcsSsb2O6izJVWrhKZz1tbzgkfY1lDgcqGV+0MHx9545BG8+j33C/po2QjatjO5g6arki2qwS8EwhQ+mUAh+KBIyLpnpbPY+NZrCb/MFMBLgunYyL0JzZGM75t3S1JwCbP2J/G0Kpg5xwQyoUlPsKxLgE="
  matrix:
    - INTEGRATION_TARGET=
    - INTEGRATION_TARGET=fec
    - INTEGRATION_TARGET=atf
script:
  - ./test-travis.sh
after_success:
  - if [[ $INTEGRATION_TARGET = '' ]]; then coveralls; fi
