language: python
sudo: false
python:
  - "2.7"
install:
  - pip install -r requirements.txt
  - pip install -r requirements_test.txt
  - pip install coveralls
env:
  - INTEGRATION_TARGET=
  - INTEGRATION_TARGET=fec
  - INTEGRATION_TARGET=atf
script:
  - |
    if [[ $INTEGRATION_TARGET = '' ]]; then
      nosetests --with-cov --cov-report term-missing --cov regparser
      flake8 .
    else
      eregs clear
      eregs integration_test $INTEGRATION_TARGET
    fi
after_success:
  - |
    if [[ $INTEGRATION_TARGET = '' ]]; then
      coveralls
    fi
