language: python
sudo: false
python:
  - "2.7"
cache: pip
install:
  - pip install -U pip wheel
  - pip install -r requirements.txt
  - pip install -r requirements_test.txt
  - pip install coveralls
env:
  - INTEGRATION_TARGET=
  - INTEGRATION_TARGET=fec
  - INTEGRATION_TARGET=atf
script:
  - ./test-travis.sh
after_success:
  - if [[ $INTEGRATION_TARGET = '' ]]; then coveralls; fi
